### ISSUE TITLE
UTL is a private repo?

### ISSUE THREAD

**Issue by jcredland** [nth-eye/QR-cpp#1]
Code won't clone as a result.  Cheers :)

```
➜  lib (main) git submodule init
Submodule 'lib/utl' (https://github.com/nth-eye/utl) registered for path 'utl'
➜  lib (main) gsu
Cloning into '/Users/jim/tmp/qr/lib/utl'...
Username for 'https://github.com':```

**Comment by nth-eye** [comment]
Oh, thank you for noticing. Yeah, some time ago I deleted the repository and moved its functions into another one. I will copy those functions into this repo and remove submodule dependency completely to avoid such issues in the future.
